### ISSUE TITLE
broctl doctor.bro fails when running all checks

### ISSUE THREAD

**Issue by m1357** [ncsa/bro-doctor#2]
When run with no arguments: 

Traceback (most recent call last):
  File "/opt/app/bro/bin/broctl", line 833, in <module>
    sys.exit(main())
  File "/opt/app/bro/bin/broctl", line 809, in main
    cmdsuccess = loop.onecmd(cmdline)
  File "/usr/local/lib/python2.7/cmd.py", line 220, in onecmd
    return self.default(line)
  File "/opt/app/bro/bin/broctl", line 54, in default
    results = self.broctl.plugincmd(cmd, cmdargs)
  File "/opt/app/bro/lib/broctl/BroControl/broctl.py", line 54, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/app/bro/lib/broctl/BroControl/broctl.py", line 34, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/app/bro/lib/broctl/BroControl/broctl.py", line 524, in plugincmd
    return self.plugins.runCustomCommand(cmd, args, self.ui)
  File "/opt/app/bro/lib/broctl/BroControl/pluginreg.py", line 157, in runCustomCommand
    return myplugin.cmd_custom(cmd, args, cmdout)
  File "/opt/app/bro/lib/bro/plugins/packages/bro-doctor/doctor.py", line 388, in cmd_custom
    results.ok = f() and results.ok
  File "/opt/app/bro/lib/bro/plugins/packages/bro-doctor/doctor.py", line 205, in check_capture_loss
    for rec in read_bro_logs_with_line_limit(reversed(files), 10000):
  File "/opt/app/bro/lib/bro/plugins/packages/bro-doctor/doctor.py", line 104, in read_bro_logs_with_line_limit
    for rec in read_bro_log(f):
  File "/opt/app/bro/lib/bro/plugins/packages/bro-doctor/doctor.py", line 97, in read_bro_log
    for rec in reader(f):
  File "/opt/app/bro/lib/bro/plugins/packages/bro-doctor/doctor.py", line 76, in bro_json_reader
    yield json.loads(f)
  File "/usr/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer

**Comment by m1357** [comment]
I do have JSON logging output enabled.

**Comment by JustinAzoff** [comment]
probably fixed in 9ada0c259d8faffea27a289f0ef58be060682a19 tagged as 1.14.0

**Comment by JustinAzoff** [comment]
Fixed, may still be some other json related issues lurking though.
